---
title: "Example 2"
author: "Jan-Philipp Kolb, Stefan Zins and Matthias Sand"
date: "1. Februar 2016"
output: html_document
---

```{r,echo=F}
Ex <- F
library(knitr)
```


## Download ESS

- Download the ESS dataset for [Denmark](http://www.europeansocialsurvey.org/file/download?f=ESS5DK.spss.zip&c=DK&y=2010) (Sampling Data and Country File) of the 5th round


## Packages for data import

- Use the package `foreign`

```{r,message=F,warning=F}
library(foreign)
```

```{r,message=F,warning=F}
library(memisc)
```

```{r,echo=F}
## Set working directory
main.path <- "J:/Work/Statistik/Kolb/Workshops/2016/grade_sampling/"

data.path <- paste(main.path,"data/",sep="")

setwd(data.path)
```


## [Import portable spss-files](http://stackoverflow.com/questions/3136293/read-spss-file-into-r)

```{r,eval=Ex}
DK <- as.data.set(spss.portable.file("ESS5DK.por"))
SE <- as.data.set(spss.portable.file("ESS5SE.por"))
```


```{r,eval=Ex}
DK <- as.data.frame(DK)
SE <- as.data.frame(SE)
```

```{r,eval=Ex,echo=F}

```


