---
title: "Sampling and Estimation"
author: "Jan-Philipp Kolb, Stefan Zins and Matthias Sand"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r,echo=F}
ca <- T
Val_eval=F
```



## Introduction

```{r}
library(survey)
data(api)
```


## Stratification

Equal allocation:

```{r}
nh.eq <- c(20,20,20)
names(nh.eq) <- names(table(apipop$stype))

s.eq <- strSRsample(apipop$stype, nh.eq, replace=FALSE)
```

Proportional allocation:

```{r}
Nh.tab  <- table(apipop$stype)
n <- 60
nh.pr <- round(Nh.tab/sum(Nh.tab)*n)

s.pr <- strSR.sample(apipop$stype, nh.pr, replace=FALSE)
```

Optimal allocation: 

```{r}
tab.names     <- apply(expand.grid(dimnames(Nh.tab)),1,paste,collapse="_")

V.h   <- tapply(apipop$api99,apipop$stype,sd)[tab.names]
nh.op <- round((Nh.tab*V.h)/(sum(Nh.tab*V.h))*n)

s.op <- strSR.sample(apipop$stype, nh.op, replace=FALSE)
```

```{r}
pop <- apipop
pop$Nh <- table(apipop$stype)[apipop$stype]
strSRS.eq <- pop[s.eq,]
strSRS.pr <- pop[s.pr,]
strSRS.op <- pop[s.op,]
```

```{r}
svystrSRS.eq <- svydesign(ids=~cds, strata =~stype,  fpc=~Nh, data=strSRS.eq)

svymean(~api00, svystrSRS.eq)
```

```{r}
svystrSRS.pr <- svydesign(ids=~cds, strata =~stype,  fpc=~Nh, data=strSRS.pr)

svymean(~api00, svystrSRS.pr)
```

```{r}
svystrSRS.op <- svydesign(ids=~cds, strata =~stype,  fpc=~Nh, data=strSRS.op)

svymean(~api00, svystrSRS.op)
```

